random_seed: 1234
max_epoch: 8
target_height: 600
max_width: 1000
lr: 5.0e-5
# warmup_iter num from begin
warmup_iter: 4000
lr_warmup_factor: 10.0
# cooldown iter num from last
cooldown_iter: 1250000
lr_cooldown_factor: 0.1
